services:
  adat-front:
    restart: unless-stopped
    build:
      context: ./
    container_name: adat-front
    ports:
      - "3022:3022"
    networks:
      - net

networks:
  net:
    name: net-adat
    external: true
