import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../component/Header";
import FilterAll from "../component/PrincipalFilter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        <FilterAll />
        {children}
      </body>
    </html>
  );
}
